<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.opencloudb.route.function.PartitionByRangeDateHashTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2017-02-20T02:40:33" hostname="DESKTOP-T7UG6RU" time="2.335">
  <properties/>
  <testcase name="testRange" classname="org.opencloudb.route.function.PartitionByRangeDateHashTest" time="0.001"/>
  <testcase name="test" classname="org.opencloudb.route.function.PartitionByRangeDateHashTest" time="2.327"/>
  <system-out><![CDATA[10:40:34.130   WARN [Test worker-SendThread(127.0.0.1:56922)] (ClientCnxn.java:1102) -Session 0x15a59642a2e0000 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
10:40:35.630   INFO [Test worker-SendThread(127.0.0.1:56922)] (ClientCnxn.java:975) -Opening socket connection to server 127.0.0.1/127.0.0.1:56922. Will not attempt to authenticate using SASL (unknown error)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
